[package]
name = "ayagami-render"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.24", features = [ "derive" ] }
log = "0.4"
wgpu = "29.0"
ayagami = { path = "../ayagami" }
glam = { version = "0.33.1", features = ["bytemuck"] }
derive_more = { version = "2.1.1", features = ["debug", "display"] }
rayon = "1.12.0"
thiserror = "2.0.18"

[dependencies.image]
version = "0.25"
default-features = false
features = ["png", "jpeg"]

[dev-dependencies]
env_logger = "0.11"
pollster = "0.4"
winit = { version = "0.30", features = ["android-native-activity"] }
