[package]
name = "ayagami-demo"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.103"
ayagami = { path = "../../modules/ayagami" }
ayagami-render = { path = "../../modules/ayagami-render" }
chrono = "0.4.45"
eframe = "0.35.0"
egui_logger = "0.11.0"
git-version = "0.3.9"
glam = "0.33.2"
log = "0.4.33"
serde = "1.0.228"
serde_json = "1.0.150"
wgpu = "29.0"
winit = "0.30.13"
zip = { version = "8.6.0", default-features = false, features = [
    "deflate64",
    "deflate",
    "lzma",
    "time",
]}

[dependencies.image]
version = "0.25"
default-features = false
features = ["png"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"
rfd = "0.17.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.70", features = ["HtmlAnchorElement"] }
wgpu = { version = "29.0", features = ["webgl"]}
wasm-bindgen = "0.2"
