name: Deploy web demo

on:
  # We only run this on merges to demo
  push:
    branches: ["demo"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  # Single deploy job since we're just deploying
  deploy:
    name: Deploy web demo
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: 1.97.1
          override: true

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "web-demo-"

      - name: Install wasm-opt
        uses: sigoden/install-binary@v1
        with:
          repo: WebAssembly/binaryen
          tag: version_130
          name: wasm-opt

      - name: Install trunk
        uses: sigoden/install-binary@v1
        with:
          repo: trunk-rs/trunk
          tag: v0.21.14
          name: trunk

      - run: |
          .github/scripts/build_demo_web.sh --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/ayagami-demo/dist
          single-commit: true
          ssh-key: ${{ secrets.DEMO_DEPLOY_KEY }}
          repository-name: AyagamiDev/demo
